import type { CSSProperties } from "react";

/** Co-located styles for ConventionCard. */
export const s = {
  // undecided = normal/active, accepted = subtle green border (the "Accepted"
  // pill carries the state), rejected = dimmed.
  card: (accepted: boolean, rejected: boolean): CSSProperties => ({
    display: "flex",
    gap: 16,
    padding: 18,
    borderRadius: 10,
    border: "1px solid " + (accepted ? "rgba(74,222,128,0.30)" : "var(--border)"),
    background: "var(--bg-elevated)",
    opacity: rejected ? 0.55 : 1,
    transition: "border-color .12s, opacity .12s",
  }),
  main: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rule: {
    fontSize: 15,
    fontWeight: 600,
    fontStyle: "italic",
    marginBottom: 12,
    lineHeight: 1.4,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  ruleEdit: { marginBottom: 12, display: "flex", gap: 8, alignItems: "center" } satisfies CSSProperties,
  evidence: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  evidenceHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 12px",
    borderBottom: "1px solid var(--border)",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
  } satisfies CSSProperties,
  evidenceLink: { color: "var(--accent-text)", textDecoration: "none" } satisfies CSSProperties,
  copyBtn: {
    marginLeft: "auto",
    background: "none",
    border: "none",
    color: "var(--text-muted)",
    cursor: "pointer",
    display: "inline-flex",
    padding: 2,
  } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "12px 14px",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12.5,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    maxHeight: 160,
    overflow: "auto",
  } satisfies CSSProperties,
  confRow: { display: "flex", alignItems: "center", gap: 10, marginTop: 12 } satisfies CSSProperties,
  confLabel: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  confTrack: {
    flex: "0 0 160px",
    height: 6,
    borderRadius: 99,
    background: "var(--bg-hover)",
    overflow: "hidden",
  } satisfies CSSProperties,
  confFill: (pct: number, color: string): CSSProperties => ({
    width: `${pct}%`,
    height: "100%",
    background: color,
    borderRadius: 99,
  }),
  confPct: { fontSize: 12, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  actions: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    flexShrink: 0,
    width: 150,
  } satisfies CSSProperties,
  acceptedPill: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--ok)",
    background: "var(--ok-bg, rgba(74,222,128,0.12))",
    border: "1px solid var(--ok)",
    borderRadius: 6,
    padding: "5px 9px",
  } satisfies CSSProperties,
} as const;
