import type { PostAs } from './types.js';

/**
 * DOMAIN CORE — the generated GitHub Actions workflow. Zero I/O.
 *
 * **This file is the feature's security boundary.** Every criterion in the
 * AC-17 – AC-26 block is satisfied or missed here, and none of them fails a
 * test at runtime: a wrong `permissions:` map or a dropped fork guard silently
 * widens a token's scope inside SOMEONE ELSE'S repository.
 *
 * The design mock-up's `YAML_PREVIEW` is deliberately NOT the source: it has no
 * `permissions:` block, no fork guard, no concurrency group, no timeout, no
 * `persist-credentials: false` and no artifact upload, and its `run:` line
 * passes CLI flags the runner does not accept. The spec's YAML is authoritative.
 *
 * Emitted as a TEMPLATE STRING, never round-tripped through a YAML emitter: an
 * emitter drops every comment, and the comments are an explicit requirement —
 * the user must be able to read and justify every line.
 */

/** Activity types GitHub actually defines for the `pull_request` event. */
const VALID_TRIGGERS = [
  'assigned',
  'unassigned',
  'labeled',
  'unlabeled',
  'opened',
  'edited',
  'closed',
  'reopened',
  'synchronize',
  'converted_to_draft',
  'ready_for_review',
  'locked',
  'unlocked',
  'review_requested',
  'review_request_removed',
  'auto_merge_enabled',
  'auto_merge_disabled',
  'milestoned',
  'demilestoned',
] as const;

export const DEFAULT_TRIGGERS = ['opened', 'synchronize'];

const VALID_POST_AS: PostAs[] = ['github_review', 'pr_comment', 'none'];

/**
 * Normalise the caller's trigger set before it reaches the generated YAML.
 *
 * The list arrives from the client as free-form strings, and it is interpolated
 * into a file that GitHub executes — so it is filtered against an allowlist,
 * de-duplicated, and ordered canonically. An empty result falls back to the
 * default pair rather than emitting `types: []`, which would silently disable
 * the workflow (AC-74's "the trigger set can never become empty").
 */
export function normalizeTriggers(triggers: readonly string[] | null | undefined): string[] {
  const allowed = new Set<string>(VALID_TRIGGERS);
  const picked = new Set((triggers ?? []).filter((t) => allowed.has(t)));
  if (picked.size === 0) return [...DEFAULT_TRIGGERS];
  return VALID_TRIGGERS.filter((t) => picked.has(t));
}

/** Constrain `post_as` to the three values the runner understands (AC-19). */
export function normalizePostAs(postAs: string | null | undefined): PostAs {
  return VALID_POST_AS.includes(postAs as PostAs) ? (postAs as PostAs) : 'github_review';
}

export interface RenderWorkflowInput {
  triggers: readonly string[];
  postAs: PostAs;
  workflowVersion: number;
}

export function renderWorkflow({
  triggers,
  postAs,
  workflowVersion,
}: RenderWorkflowInput): string {
  const types = normalizeTriggers(triggers).join(', ');
  const post = normalizePostAs(postAs);

  return `# Generated by DevDigest · Export to CI · workflow v${workflowVersion}
# Safe to edit: re-exporting this agent replaces this file.
name: DevDigest Review

# ONLY pull_request. Never pull_request_target (it would run with a privileged
# token in the base-repo context) and never issue_comment or any other
# comment-driven trigger — comment text is attacker-controlled input, never a
# command channel.
on:
  pull_request:
    types: [${types}]

# Least privilege. contents:read to check out .devdigest/, pull-requests:write
# to post the review. Nothing wider "just in case".
permissions:
  contents: read
  pull-requests: write

# One review in flight per PR; a new push cancels the previous run.
concurrency:
  group: devdigest-review-\${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    # A PR from a fork receives NO repository secrets, so the review could only
    # start with an empty API key and fail. Skip it outright and say so.
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out the pull request
        uses: actions/checkout@v4
        with:
          # Do not leave the job token in .git/config for a later step to read.
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run DevDigest review
        # The reviewer is vendored in this repository under .devdigest/runner/
        # and was reviewed in the same pull request that added this file. No
        # marketplace action, so nothing outside this repo can change what runs.
        # The runner takes no CLI flags — everything is passed as env.
        run: node .devdigest/runner/index.js
        env:
          # Credentials come from this repository's Actions secrets ONLY. They
          # appear in no committed file and in no agent manifest.
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: \${{ github.repository }}
          PR_NUMBER: \${{ github.event.pull_request.number }}
          DEVDIGEST_POST_AS: ${post}

      - name: Upload result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: devdigest-result
          path: devdigest-result.json
          if-no-files-found: warn
          compression-level: 0
`;
}
