import { describe, it, expect } from 'vitest';
import YAML from 'yaml';
import { renderWorkflow, normalizeTriggers, normalizePostAs } from './workflow.js';

/**
 * The generated workflow IS the security boundary (AC-17 – AC-26). Every
 * assertion below parses the emitted YAML rather than string-matching, so a
 * reformat cannot quietly satisfy the test while changing the semantics.
 */

const render = (over: Partial<Parameters<typeof renderWorkflow>[0]> = {}) =>
  renderWorkflow({
    triggers: ['opened', 'synchronize'],
    postAs: 'github_review',
    workflowVersion: 1,
    ...over,
  });

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const parse = (yaml: string): any => YAML.parse(yaml);

describe('renderWorkflow', () => {
  it('parses as valid YAML and names the workflow', () => {
    const doc = parse(render());
    expect(doc.name).toBe('DevDigest Review');
  });

  it('carries the generated-by header with the workflow version', () => {
    expect(render({ workflowVersion: 7 })).toContain(
      '# Generated by DevDigest · Export to CI · workflow v7',
    );
    expect(render()).toContain('# Safe to edit: re-exporting this agent replaces this file.');
  });

  it('grants EXACTLY contents:read + pull-requests:write and nothing else (AC-17)', () => {
    const doc = parse(render());
    expect(doc.permissions).toEqual({ contents: 'read', 'pull-requests': 'write' });
    expect(Object.keys(doc.permissions)).toHaveLength(2);
  });

  it('obtains every credential only via secrets.* interpolation (AC-18)', () => {
    const yaml = render();
    const env = parse(yaml).jobs.review.steps[2].env;
    expect(env.OPENROUTER_API_KEY).toBe('${{ secrets.OPENROUTER_API_KEY }}');
    expect(env.GITHUB_TOKEN).toBe('${{ secrets.GITHUB_TOKEN }}');
    // No literal key material anywhere in the file.
    expect(yaml).not.toMatch(/sk-[A-Za-z0-9]{8,}/);
    expect(yaml).not.toMatch(/gh[ps]_[A-Za-z0-9]{20,}/);
    for (const line of yaml.split('\n')) {
      if (/API_KEY:|_TOKEN:/.test(line) && !line.trim().startsWith('#')) {
        expect(line).toContain('${{ secrets.');
      }
    }
  });

  it('passes post_as as DEVDIGEST_POST_AS in env (AC-19)', () => {
    for (const postAs of ['github_review', 'pr_comment', 'none'] as const) {
      const env = parse(render({ postAs })).jobs.review.steps[2].env;
      expect(env.DEVDIGEST_POST_AS).toBe(postAs);
    }
  });

  it('guards the job against fork pull requests, in the exact form (AC-20)', () => {
    const doc = parse(render());
    expect(doc.jobs.review.if).toBe(
      'github.event.pull_request.head.repo.full_name == github.repository',
    );
  });

  it('triggers on pull_request ONLY (AC-21)', () => {
    const doc = parse(render());
    expect(Object.keys(doc.on)).toEqual(['pull_request']);
    for (const forbidden of [
      'pull_request_target',
      'issue_comment',
      'pull_request_review_comment',
      'workflow_run',
      'workflow_dispatch',
      'schedule',
    ]) {
      expect(doc.on[forbidden]).toBeUndefined();
      expect(render()).not.toContain(`${forbidden}:`);
    }
  });

  it('reflects the active trigger chips in types: (AC-73)', () => {
    expect(parse(render()).on.pull_request.types).toEqual(['opened', 'synchronize']);
    expect(
      parse(render({ triggers: ['opened', 'synchronize', 'reopened'] })).on.pull_request.types,
    ).toEqual(['opened', 'reopened', 'synchronize']);
  });

  it('disables credential persistence on checkout (AC-22)', () => {
    const checkout = parse(render()).jobs.review.steps[0];
    expect(checkout.uses).toBe('actions/checkout@v4');
    expect(checkout.with['persist-credentials']).toBe(false);
  });

  it('uses ONLY first-party actions/* and names no DevDigest action (AC-23)', () => {
    const doc = parse(render());
    const uses = doc.jobs.review.steps
      .map((s: { uses?: string }) => s.uses)
      .filter((u: string | undefined): u is string => Boolean(u));
    expect(uses.length).toBeGreaterThan(0);
    for (const u of uses) {
      expect(u.startsWith('actions/')).toBe(true);
      expect(u.toLowerCase()).not.toContain('devdigest');
    }
  });

  it('bounds the job with timeout-minutes (AC-24)', () => {
    expect(parse(render()).jobs.review['timeout-minutes']).toBe(15);
  });

  it('declares a per-PR concurrency group with cancellation (AC-25)', () => {
    const doc = parse(render());
    expect(doc.concurrency.group).toBe(
      'devdigest-review-${{ github.event.pull_request.number }}',
    );
    expect(doc.concurrency['cancel-in-progress']).toBe(true);
  });

  it('uploads the result unconditionally, uncompressed, non-fatally (AC-26)', () => {
    const upload = parse(render()).jobs.review.steps[3];
    expect(upload.uses).toBe('actions/upload-artifact@v4');
    expect(upload.if).toBe('always()');
    expect(upload.with.name).toBe('devdigest-result');
    expect(upload.with.path).toBe('devdigest-result.json');
    expect(upload.with['if-no-files-found']).toBe('warn');
    expect(upload.with['compression-level']).toBe(0);
  });

  it('invokes the vendored runner by path with NO CLI flags (spec deviations 2 & 3)', () => {
    const run = parse(render()).jobs.review.steps[2].run;
    expect(run).toBe('node .devdigest/runner/index.js');
    // The design's fabricated line must never reappear.
    expect(render()).not.toContain('runner.mjs');
    expect(render()).not.toContain('--fail-on');
    expect(render()).not.toContain('--agent');
  });

  it('keeps every explanatory comment (the user must be able to justify each line)', () => {
    const yaml = render();
    for (const comment of [
      '# ONLY pull_request. Never pull_request_target',
      '# Least privilege.',
      '# One review in flight per PR',
      '# A PR from a fork receives NO repository secrets',
      '# Do not leave the job token in .git/config',
      '# The runner takes no CLI flags',
      "# Credentials come from this repository's Actions secrets ONLY.",
    ]) {
      expect(yaml).toContain(comment);
    }
  });
});

describe('input normalisation (untrusted client values reach a file GitHub executes)', () => {
  it('drops trigger values outside GitHub’s pull_request activity types', () => {
    expect(normalizeTriggers(['opened', 'evil]\njobs:\n  pwn:'])).toEqual(['opened']);
    expect(parse(render({ triggers: ['opened', ']}\nmalicious: true'] })).on.pull_request.types)
      .toEqual(['opened']);
  });

  it('never emits an empty trigger set (AC-74)', () => {
    expect(normalizeTriggers([])).toEqual(['opened', 'synchronize']);
    expect(normalizeTriggers(undefined)).toEqual(['opened', 'synchronize']);
    expect(normalizeTriggers(['nonsense'])).toEqual(['opened', 'synchronize']);
  });

  it('de-duplicates and canonically orders triggers', () => {
    expect(normalizeTriggers(['synchronize', 'opened', 'opened'])).toEqual([
      'opened',
      'synchronize',
    ]);
  });

  it('constrains post_as to the three runner-understood values', () => {
    expect(normalizePostAs('pr_comment')).toBe('pr_comment');
    expect(normalizePostAs('none')).toBe('none');
    expect(normalizePostAs('anything-else')).toBe('github_review');
    expect(normalizePostAs(null)).toBe('github_review');
  });
});
