import type { CSSProperties } from "react";

/** Co-located styles for ImportSkillDrawer. */
export const s = {
  body: { padding: 24, overflow: "auto", display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  footer: { display: "flex", gap: 10, justifyContent: "flex-end" } satisfies CSSProperties,
  trust: {
    display: "flex",
    gap: 10,
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    background: "var(--accent-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "10px 14px",
  } satisfies CSSProperties,
  error: {
    fontSize: 13,
    color: "var(--crit, #f87171)",
    background: "var(--crit-bg, #2e0a0a)",
    border: "1px solid var(--crit, #f87171)",
    borderRadius: 8,
    padding: "10px 14px",
  } satisfies CSSProperties,
  preview: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  previewHead: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  previewName: { fontSize: 15, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  previewDesc: { fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  notes: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    fontStyle: "italic",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  ignored: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "10px 14px",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  ignoredHead: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  ignoredList: {
    margin: 0,
    paddingLeft: 18,
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.6,
  } satisfies CSSProperties,
  bodyLabel: {
    fontSize: 12,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  markdown: {
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "12px 16px",
    maxHeight: 320,
    overflow: "auto",
  } satisfies CSSProperties,
} as const;
