/* styles.ts — co-located styles for the CI Runs page.
   Values track design-src/screen_cizruns.jsx (ScreenCIRuns, :18-52). */
import type { CSSProperties } from "react";
import { GRID } from "./constants";

export const s = {
  header: {
    padding: "20px 28px 6px",
    display: "flex",
    alignItems: "flex-end",
    gap: 12,
  } satisfies CSSProperties,
  h1: { fontSize: 22, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-secondary)", marginTop: 3 } satisfies CSSProperties,
  headerActions: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  autoRefresh: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
  } satisfies CSSProperties,
  autoRefreshDot: {
    width: 6,
    height: 6,
    borderRadius: 99,
    background: "var(--ok)",
  } satisfies CSSProperties,
  refreshOutcome: {
    padding: "0 28px",
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  refreshError: {
    padding: "0 28px",
    fontSize: 12,
    color: "var(--crit)",
  } satisfies CSSProperties,
  filters: {
    display: "flex",
    gap: 8,
    padding: "12px 28px",
    flexWrap: "wrap",
  } satisfies CSSProperties,
  tableCard: {
    margin: "6px 28px 40px",
    border: "1px solid var(--border)",
    borderRadius: 10,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  headRow: {
    display: "grid",
    gridTemplateColumns: GRID,
    gap: 12,
    padding: "10px 16px",
    background: "var(--bg-surface)",
    borderBottom: "1px solid var(--border)",
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  row: (last: boolean): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: GRID,
    gap: 12,
    padding: "12px 16px",
    borderBottom: last ? "none" : "1px solid var(--border)",
    alignItems: "center",
    fontSize: 12.5,
  }),
  ts: { fontSize: 11, color: "var(--text-secondary)" } satisfies CSSProperties,
  prCell: { minWidth: 0 } satisfies CSSProperties,
  prNumber: { fontSize: 11, color: "var(--accent-text)" } satisfies CSSProperties,
  prTitle: {
    fontSize: 12.5,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "inline-block",
    verticalAlign: "bottom",
    maxWidth: "85%",
  } satisfies CSSProperties,
  agentCell: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-secondary)",
    minWidth: 0,
  } satisfies CSSProperties,
  agentIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  agentName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  duration: { fontSize: 12 } satisfies CSSProperties,
  cost: { fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  dash: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  findingsCell: { display: "flex", gap: 7 } satisfies CSSProperties,
  findingPair: (color: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    fontSize: 11.5,
    fontWeight: 600,
    color,
  }),
  loading: { padding: "6px 28px", display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
} as const;
