import type { CSSProperties } from "react";

/** Co-located styles for the agent editor's Context tab (mirrors SkillsTab). */
export const s = {
  wrap: { maxWidth: 820 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 6 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  count: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--accent)",
    background: "var(--accent-bg)",
    padding: "2px 10px",
    borderRadius: 5,
  } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 220,
  } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-secondary)", margin: "10px 0 16px", lineHeight: 1.5 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: (attached: boolean, dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid " + (attached ? "var(--border-strong)" : "var(--border)"),
    background: attached ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: dragging ? 0.5 : 1,
  }),
  grip: (draggable: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    cursor: draggable ? "grab" : "default",
    display: "inline-flex",
    opacity: draggable ? 1 : 0.25,
  }),
  rowText: { display: "flex", alignItems: "baseline", gap: 8, flex: 1, minWidth: 0 } satisfies CSSProperties,
  name: {
    fontSize: 13,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  dir: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono, monospace)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  tokens: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  preview: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: "14px 18px",
    fontSize: 13.5,
    color: "var(--text-secondary)",
    maxHeight: 360,
    overflowY: "auto",
  } satisfies CSSProperties,
  previewLoading: { display: "flex", flexDirection: "column", gap: 8, padding: 14 } satisfies CSSProperties,
  previewError: { fontSize: 13, color: "var(--crit)", padding: "10px 14px" } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: 14,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  empty: {
    fontSize: 13,
    color: "var(--text-secondary)",
    border: "1px dashed var(--border)",
    borderRadius: 8,
    padding: "20px 16px",
    textAlign: "center",
    lineHeight: 1.6,
  } satisfies CSSProperties,
} as const;
