/**
 * ExportWizard — the 4-step Export to CI modal.
 *
 * Covers the shell (AC-62), the target grid and its three inert cards
 * (AC-63 – AC-65), the constrained repository picker (AC-66), the provider and
 * already-claimed blocks (AC-67, AC-68), the server-driven preview with its
 * runner placeholder and single editable pane (AC-69 – AC-71), the
 * regenerate-on-config-change notice (AC-72), the trigger chips and their
 * mandatory pair (AC-73, AC-74), the `Post results as` radios (AC-75), the
 * `blockMergeInfo` card (AC-76, AC-82), and the install / zip cards
 * (AC-77, AC-78).
 *
 * Hooks mocked at the `@/lib/hooks/*` boundary. `fireEvent`, not `userEvent` —
 * the latter is not installed (client/INSIGHTS.md, 2026-07-12).
 */
import React from "react";
import { describe, it, expect, afterEach, beforeEach, vi } from "vitest";
import { render, screen, cleanup, fireEvent, waitFor, within } from "@testing-library/react";
import { NextIntlClientProvider } from "next-intl";
import type { Agent, CiExport, CiInstallation, Repo } from "@devdigest/shared";
import ciMessages from "../../../../../../../../../../messages/en/ci.json";

const WORKFLOW = `# Generated by DevDigest · Export to CI · workflow v1
name: DevDigest Review
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: write
`;

const hoisted = vi.hoisted(() => ({
  repos: [] as unknown[],
  exportData: null as unknown,
  generatePending: false,
  generateError: null as unknown,
  generateMutateAsync: vi.fn(),
  generateReset: vi.fn(),
  installMutate: vi.fn(),
  installData: null as unknown,
  installPending: false,
  installError: null as unknown,
  zipMutate: vi.fn(),
}));

vi.mock("@/lib/hooks/core", () => ({
  useRepos: () => ({ data: hoisted.repos }),
}));

vi.mock("@/lib/hooks/ci-export", () => ({
  useGenerateCiExport: () => ({
    mutateAsync: hoisted.generateMutateAsync,
    reset: hoisted.generateReset,
    data: hoisted.exportData,
    isPending: hoisted.generatePending,
    error: hoisted.generateError,
  }),
  useInstallCiExport: () => ({
    mutate: hoisted.installMutate,
    data: hoisted.installData,
    isPending: hoisted.installPending,
    error: hoisted.installError,
  }),
  useDownloadCiZip: () => ({ mutate: hoisted.zipMutate, isPending: false }),
}));

import { ExportWizard } from "./ExportWizard";

const AGENT: Agent = {
  id: "agent-1",
  name: "Security Reviewer",
  description: "Flags secrets",
  provider: "openrouter",
  model: "deepseek/deepseek-chat",
  system_prompt: "You review PRs.",
  output_schema: null,
  strategy: "single-pass",
  ci_fail_on: "critical",
  repo_intel: true,
  enabled: true,
  version: 1,
  skill_count: 1,
};

const REPOS: Repo[] = [
  {
    id: "r1",
    workspace_id: "ws-1",
    owner: "acme",
    name: "payments-api",
    full_name: "acme/payments-api",
    default_branch: "main",
    clone_path: null,
    last_polled_at: null,
    created_by: null,
  },
  {
    id: "r2",
    workspace_id: "ws-1",
    owner: "acme",
    name: "billing-worker",
    full_name: "acme/billing-worker",
    default_branch: "trunk",
    clone_path: null,
    last_polled_at: null,
    created_by: null,
  },
];

const INSTALLATION: CiInstallation = {
  id: "inst-1",
  agent_id: "agent-1",
  workspace_id: "ws-1",
  repo: "acme/payments-api",
  target_type: "gha",
  installed_at: "2026-08-01T10:00:00.000Z",
  post_as: "github_review",
  triggers: ["opened", "synchronize"],
  base: "main",
  manifest_path: ".devdigest/agents/security-reviewer.yaml",
  workflow_path: ".github/workflows/devdigest-review.yml",
  workflow_version: 1,
  pr_url: "https://github.com/acme/payments-api/pull/12",
  last_ingest_at: null,
  exported_ci_fail_on: "critical",
  status: null,
  last_activity_at: null,
  policy_drift: false,
};

const EXPORT: CiExport = {
  installation: INSTALLATION,
  files: [
    {
      path: ".devdigest/agents/security-reviewer.yaml",
      contents: "name: Security Reviewer\n",
      editable: false,
      placeholder: null,
    },
    {
      path: ".devdigest/skills/secret-leakage-gate.md",
      contents: "# Secret leakage gate\n",
      editable: false,
      placeholder: null,
    },
    { path: ".devdigest/memory.jsonl", contents: "", editable: false, placeholder: null },
    {
      path: ".devdigest/runner/index.js",
      // Defensive: even if a server ever sent bytes alongside a placeholder,
      // the client must render the placeholder and NEVER these contents.
      contents: "RUNNER_BUNDLE_BYTES_SHOULD_NEVER_RENDER",
      editable: false,
      placeholder: "1.57 MB",
    },
    {
      path: ".github/workflows/devdigest-review.yml",
      contents: WORKFLOW,
      editable: true,
      placeholder: null,
    },
  ],
  pr_url: null,
  repo: "acme/payments-api",
  file_count: 5,
};

function renderWizard(agent: Agent = AGENT, onClose = vi.fn()) {
  return render(
    <NextIntlClientProvider locale="en" messages={{ ci: ciMessages }}>
      <ExportWizard agent={agent} onClose={onClose} />
    </NextIntlClientProvider>,
  );
}

function renderUpdateWizard(installations: CiInstallation[], onClose = vi.fn()) {
  return render(
    <NextIntlClientProvider locale="en" messages={{ ci: ciMessages }}>
      <ExportWizard
        agent={AGENT}
        onClose={onClose}
        mode="update"
        installations={installations}
      />
    </NextIntlClientProvider>,
  );
}

/** Walk Target → Preview with a repository selected. */
async function goToPreview() {
  fireEvent.change(screen.getByRole("combobox"), { target: { value: "acme/payments-api" } });
  fireEvent.click(screen.getByRole("button", { name: /Continue/ }));
  await screen.findByText("FILES TO CREATE");
}

async function goToConfigure() {
  await goToPreview();
  fireEvent.click(screen.getByRole("button", { name: /Continue/ }));
  await screen.findByText("Post results as");
}

beforeEach(() => {
  hoisted.repos = REPOS;
  hoisted.exportData = null;
  hoisted.generatePending = false;
  hoisted.generateError = null;
  hoisted.installData = null;
  hoisted.installPending = false;
  hoisted.installError = null;
  hoisted.generateMutateAsync.mockImplementation(async () => {
    hoisted.exportData = EXPORT;
    return EXPORT;
  });
});

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

describe("ExportWizard — shell and Target step", () => {
  it("renders a 720-wide modal with the four-label step indicator and a Back-less first footer (AC-62)", () => {
    renderWizard();

    const dialog = screen.getByRole("dialog");
    expect(dialog).toHaveStyle({ width: "720px" });
    expect(screen.getByText("Export to CI")).toBeInTheDocument();
    expect(screen.getByText("Run Security Reviewer automatically on pull requests")).toBeInTheDocument();
    for (const label of ["Target", "Preview", "Configure", "Install"]) {
      expect(screen.getByText(label)).toBeInTheDocument();
    }
    expect(screen.queryByRole("button", { name: /Back/ })).not.toBeInTheDocument();
    expect(screen.getByRole("button", { name: /Continue/ })).toBeInTheDocument();
  });

  it("renders four target cards with `recommended` on GitHub Actions and the other three inert (AC-63 – AC-65)", () => {
    renderWizard();

    const gha = screen.getByRole("button", { name: /GitHub Actions/ });
    expect(within(gha).getByText("recommended")).toBeInTheDocument();
    expect(gha).toBeEnabled();

    for (const name of ["CircleCI", "Jenkins", "Generic CLI"]) {
      const card = screen.getByRole("button", { name: new RegExp(name) });
      expect(card).toBeDisabled();
      expect(card).toHaveAttribute("aria-disabled", "true");
      expect(within(card).getByText("coming soon")).toBeInTheDocument();
      expect(
        within(card).getByText(`${name} export is not available yet`),
      ).toBeInTheDocument();

      // Activating it changes neither the selection nor the step.
      fireEvent.click(card);
      expect(card).toHaveAttribute("aria-pressed", "false");
      expect(gha).toHaveAttribute("aria-pressed", "true");
      expect(screen.getByRole("button", { name: /Continue/ })).toBeInTheDocument();
      expect(screen.queryByRole("button", { name: /Back/ })).not.toBeInTheDocument();
    }
  });

  it("offers only workspace repositories and no free-text field (AC-66)", () => {
    renderWizard();

    expect(screen.queryByRole("textbox")).not.toBeInTheDocument();
    const options = screen.getAllByRole("option").map((o) => (o as HTMLOptionElement).value);
    expect(options).toEqual(["", "acme/payments-api", "acme/billing-worker"]);
  });

  it("blocks a non-OpenRouter agent with an inline explanation and a disabled Continue (AC-67)", () => {
    renderWizard({ ...AGENT, provider: "openai" });

    expect(screen.getByRole("alert")).toHaveTextContent(
      "This agent runs on openai. The CI runner only executes OpenRouter agents",
    );
    expect(screen.getByRole("button", { name: /Continue/ })).toBeDisabled();
  });

  it("surfaces the server's already-claimed message and does NOT advance (AC-68)", async () => {
    hoisted.generateMutateAsync.mockRejectedValue(
      new Error("acme/payments-api already runs Perf Reviewer in CI. One agent per repository."),
    );
    hoisted.generateError = new Error(
      "acme/payments-api already runs Perf Reviewer in CI. One agent per repository.",
    );
    renderWizard();

    fireEvent.change(screen.getByRole("combobox"), { target: { value: "acme/payments-api" } });
    fireEvent.click(screen.getByRole("button", { name: /Continue/ }));

    await waitFor(() =>
      expect(screen.getByRole("alert")).toHaveTextContent("already runs Perf Reviewer in CI"),
    );
    // Still on Target: no Back button, and the repository picker is visible.
    expect(screen.queryByRole("button", { name: /Back/ })).not.toBeInTheDocument();
    expect(screen.getByRole("combobox")).toBeInTheDocument();
  });
});

describe("ExportWizard — Preview step", () => {
  it("renders the SERVER's file tree including the runner entries (AC-69)", async () => {
    renderWizard();
    await goToPreview();

    for (const path of EXPORT.files.map((f) => f.path)) {
      // The selected file's path also appears in the pane header, hence *All*.
      expect(screen.getAllByText(path).length).toBeGreaterThan(0);
    }
    expect(hoisted.generateMutateAsync).toHaveBeenCalledWith({
      agentId: "agent-1",
      input: {
        repo: "acme/payments-api",
        target: "gha",
        post_as: "github_review",
        triggers: ["opened", "synchronize"],
        base: "main",
      },
    });
  });

  it("makes ONLY the workflow pane editable and shows the runner placeholder instead of bundle bytes (AC-70, AC-71)", async () => {
    renderWizard();
    await goToPreview();

    // The workflow is selected by default: editable badge + a real editor.
    expect(screen.getByText("editable")).toBeInTheDocument();
    const editor = screen.getByRole("textbox", {
      name: ".github/workflows/devdigest-review.yml",
    });
    expect(editor).toHaveValue(WORKFLOW);

    // The manifest pane is read-only.
    fireEvent.click(screen.getByText(".devdigest/agents/security-reviewer.yaml"));
    expect(screen.queryByRole("textbox")).not.toBeInTheDocument();
    expect(screen.queryByText("editable")).not.toBeInTheDocument();

    // The runner pane renders the placeholder — never its contents.
    fireEvent.click(screen.getByText(".devdigest/runner/index.js"));
    expect(screen.getByText("Runner bundle · 1.57 MB · contents not shown")).toBeInTheDocument();
    expect(screen.queryByText(/RUNNER_BUNDLE_BYTES_SHOULD_NEVER_RENDER/)).not.toBeInTheDocument();
    expect(screen.queryByRole("textbox")).not.toBeInTheDocument();
  });
});

describe("ExportWizard — Configure step", () => {
  it("renders the three trigger chips with the mandatory pair active and undeselectable (AC-73, AC-74)", async () => {
    renderWizard();
    await goToConfigure();

    const opened = screen.getByRole("button", { name: /pull_request:opened/ });
    const sync = screen.getByRole("button", { name: /pull_request:synchronize/ });
    const reopened = screen.getByRole("button", { name: /pull_request:reopened/ });

    expect(opened).toHaveTextContent("required");
    expect(sync).toHaveTextContent("required");
    expect(opened.style.background).toContain("--accent-bg");
    expect(sync.style.background).toContain("--accent-bg");
    expect(reopened.style.background).not.toContain("--accent-bg");

    const callsBefore = hoisted.generateMutateAsync.mock.calls.length;
    fireEvent.click(opened);
    fireEvent.click(sync);
    // Still active, and no regeneration for a change that never happened.
    expect(opened.style.background).toContain("--accent-bg");
    expect(sync.style.background).toContain("--accent-bg");
    expect(hoisted.generateMutateAsync.mock.calls).toHaveLength(callsBefore);

    fireEvent.click(reopened);
    await waitFor(() =>
      expect(hoisted.generateMutateAsync).toHaveBeenLastCalledWith(
        expect.objectContaining({
          input: expect.objectContaining({ triggers: ["opened", "synchronize", "reopened"] }),
        }),
      ),
    );
  });

  it("renders the three post-as radios with GitHub review selected and badged, plus the blockMergeInfo card (AC-75, AC-76, AC-82)", async () => {
    renderWizard();
    await goToConfigure();

    const group = screen.getByRole("radiogroup", { name: "Post results as" });
    expect(within(group).getByRole("radio", { name: /GitHub review/ })).toBeChecked();
    expect(within(group).getByRole("radio", { name: "PR comment" })).not.toBeChecked();
    expect(within(group).getByRole("radio", { name: "None (exit code only)" })).not.toBeChecked();
    expect(screen.getByText("Only GitHub review yields a verdict on the pull request.")).toBeInTheDocument();

    expect(screen.getByText(/No GitHub App needed\./)).toBeInTheDocument();
    // The stale, contradictory `blockMergeDesc` copy is referenced nowhere.
    expect(screen.queryByText(/Requires a GitHub App/)).not.toBeInTheDocument();
  });

  it("regenerates the workflow AND says so when a Configure change replaces a hand-edit (AC-72)", async () => {
    renderWizard();
    await goToPreview();

    fireEvent.change(
      screen.getByRole("textbox", { name: ".github/workflows/devdigest-review.yml" }),
      { target: { value: `${WORKFLOW}# my hand edit\n` } },
    );
    fireEvent.click(screen.getByRole("button", { name: /Continue/ }));
    await screen.findByText("Post results as");
    expect(
      screen.queryByText(
        "Your edits to the workflow were replaced because the configuration changed.",
      ),
    ).not.toBeInTheDocument();

    const callsBefore = hoisted.generateMutateAsync.mock.calls.length;
    fireEvent.click(screen.getByRole("button", { name: /pull_request:reopened/ }));

    await screen.findByText(
      "Your edits to the workflow were replaced because the configuration changed.",
    );
    expect(hoisted.generateMutateAsync.mock.calls.length).toBe(callsBefore + 1);
    // The dropped edit is never sent back to the server.
    expect(hoisted.generateMutateAsync.mock.calls.at(-1)![0].input.workflow).toBeUndefined();
  });
});

describe("ExportWizard — Install step", () => {
  async function goToInstall() {
    await goToConfigure();
    fireEvent.click(screen.getByRole("button", { name: /Continue/ }));
    await screen.findByText("Open a PR with these files");
  }

  it("names the repository and the file count and installs on activation (AC-77)", async () => {
    renderWizard();
    await goToInstall();

    expect(
      screen.getByText(
        /DevDigest opens a PR in acme\/payments-api titled .* with the 5 generated files\./,
      ),
    ).toBeInTheDocument();
    // The secret requirement lives on Configure now; Install carries the
    // design's setup-docs link instead.
    const docs = screen.getByRole("link", { name: /GitHub Actions secrets docs/ });
    expect(docs).toHaveAttribute("href", expect.stringContaining("docs.github.com"));
    expect(
      screen.queryByText(/Add OPENROUTER_API_KEY to the repo's Actions secrets/),
    ).not.toBeInTheDocument();

    fireEvent.click(screen.getByText("Open a PR with these files"));
    expect(hoisted.installMutate).toHaveBeenCalledWith({
      agentId: "agent-1",
      input: {
        repo: "acme/payments-api",
        target: "gha",
        post_as: "github_review",
        triggers: ["opened", "synchronize"],
        base: "main",
      },
    });
  });

  it("shows a distinct in-progress state for the whole install", async () => {
    hoisted.installPending = true;
    renderWizard();
    await goToInstall();

    expect(screen.getAllByText("Installing…").length).toBeGreaterThan(0);
  });

  it("surfaces the opened pull request as a new-tab link on success (AC-77)", async () => {
    hoisted.installData = { ...EXPORT, pr_url: "https://github.com/acme/payments-api/pull/12" };
    renderWizard();
    await goToInstall();

    expect(screen.getByText("Pull request opened")).toBeInTheDocument();
    const link = screen.getByRole("link", { name: "View pull request" });
    expect(link).toHaveAttribute("href", "https://github.com/acme/payments-api/pull/12");
    expect(link).toHaveAttribute("target", "_blank");
    expect(link).toHaveAttribute("rel", "noopener noreferrer");
  });

  it("surfaces an install failure without recording anything", async () => {
    hoisted.installError = new Error("GitHub rejected the commit");
    renderWizard();
    await goToInstall();

    expect(screen.getByRole("alert")).toHaveTextContent("Install failed — nothing was committed.");
    expect(screen.getByRole("alert")).toHaveTextContent("GitHub rejected the commit");
  });

  it("downloads the zip without firing install or another generation (AC-78)", async () => {
    renderWizard();
    await goToInstall();

    const callsBefore = hoisted.generateMutateAsync.mock.calls.length;
    fireEvent.click(screen.getByText("Copy files as a zip"));

    expect(hoisted.zipMutate).toHaveBeenCalledTimes(1);
    expect(hoisted.installMutate).not.toHaveBeenCalled();
    expect(hoisted.generateMutateAsync.mock.calls).toHaveLength(callsBefore);
  });
});

describe("ExportWizard — after a successful install", () => {
  beforeEach(() => {
    hoisted.installData = { pr_url: "https://github.com/acme/payments-api/pull/12" };
  });

  it("swaps the primary action for an explicit exit instead of closing itself", async () => {
    const onClose = vi.fn();
    renderWizard(AGENT, onClose);
    await goToConfigure();
    fireEvent.click(screen.getByRole("button", { name: /Continue/ }));
    await screen.findByText("Pull request opened");

    // The modal stays open — the PR link is the payoff of this step.
    expect(onClose).not.toHaveBeenCalled();
    expect(screen.getByRole("link", { name: "View pull request" })).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: /Done/ }));
    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it("cannot open a second pull request for the same export", async () => {
    renderWizard();
    await goToConfigure();
    fireEvent.click(screen.getByRole("button", { name: /Continue/ }));
    await screen.findByText("Pull request opened");

    expect(screen.queryByRole("button", { name: /^Install$/ })).not.toBeInTheDocument();
    fireEvent.click(screen.getByText("Open a PR with these files"));
    expect(hoisted.installMutate).not.toHaveBeenCalled();
  });
});

describe("ExportWizard — update mode", () => {
  const OTHER: CiInstallation = {
    ...INSTALLATION,
    id: "inst-2",
    repo: "acme/billing-worker",
    post_as: "pr_comment",
    triggers: ["opened", "synchronize", "reopened"],
    base: "trunk",
  };

  it("opens on the live settings rather than on defaults", async () => {
    renderUpdateWizard([OTHER]);

    expect(screen.getByText("Update CI config")).toBeInTheDocument();
    expect(screen.getByRole("combobox")).toHaveValue("acme/billing-worker");

    fireEvent.click(screen.getByRole("button", { name: /Continue/ }));
    await screen.findByText("FILES TO CREATE");
    fireEvent.click(screen.getByRole("button", { name: /Continue/ }));
    await screen.findByText("Post results as");

    // Seeded from the installation, not from the create-mode defaults.
    expect(screen.getByRole("radio", { name: /PR comment/ })).toBeChecked();
    expect(screen.getByRole("button", { name: /pull_request:reopened/ })).toBeInTheDocument();
  });

  it("restricts the picker to installed repos and re-seeds when switching", () => {
    renderUpdateWizard([INSTALLATION, OTHER]);
    const select = screen.getByRole("combobox");

    // `acme/billing-worker` is installed too, so both appear — but nothing else,
    // and there is no blank "choose a repo" entry to fall back to.
    const values = Array.from(select.querySelectorAll("option")).map((o) => o.value);
    expect(values).toContain("acme/payments-api");
    expect(values).toContain("acme/billing-worker");

    fireEvent.change(select, { target: { value: "acme/billing-worker" } });
    expect(select).toHaveValue("acme/billing-worker");
  });
});
