import type { CSSProperties } from "react";

/** Co-located styles for the Export Wizard.
    Values taken verbatim from `design-src/screen_export.jsx`. */
export const s = {
  /* --- shell (:104-111) --- */
  stepsBar: {
    padding: "18px 20px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  body: { padding: 20 } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center" } satisfies CSSProperties,
  footerRight: { marginLeft: "auto" } satisfies CSSProperties,
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0 0 0 0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,

  /* --- Target step (:54-62) --- */
  targetGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  } satisfies CSSProperties,
  targetCard: (selected: boolean, available: boolean): CSSProperties => ({
    textAlign: "left",
    padding: 16,
    borderRadius: 10,
    cursor: available ? "pointer" : "not-allowed",
    background: "var(--bg-surface)",
    border: "1.5px solid " + (selected ? "var(--accent)" : "var(--border)"),
    fontFamily: "inherit",
    opacity: available ? 1 : 0.55,
  }),
  targetHead: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  targetIcon: (selected: boolean, available: boolean): CSSProperties => ({
    width: 34,
    height: 34,
    borderRadius: 8,
    background: "var(--bg-elevated)",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    color: !available
      ? "var(--text-muted)"
      : selected
        ? "var(--accent)"
        : "var(--text-secondary)",
  }),
  targetName: (available: boolean): CSSProperties => ({
    fontSize: 14,
    fontWeight: 600,
    color: available ? "var(--text-primary)" : "var(--text-muted)",
  }),
  targetDesc: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginTop: 8,
  } satisfies CSSProperties,
  repoField: { marginTop: 20 } satisfies CSSProperties,
  blockNotice: {
    display: "flex",
    alignItems: "flex-start",
    gap: 9,
    marginTop: 14,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,

  /* --- Preview step (:64-72) --- */
  previewWrap: {
    display: "grid",
    gridTemplateColumns: "260px 1fr",
    gap: 0,
    height: 340,
    border: "1px solid var(--border)",
    borderRadius: 9,
    overflow: "hidden",
  } satisfies CSSProperties,
  tree: {
    borderRight: "1px solid var(--border)",
    padding: 10,
    background: "var(--bg-surface)",
    overflow: "auto",
    // Grid items default to `min-height: auto`, which lets them grow past their
    // track instead of scrolling — the wrapper's `overflow: hidden` then just
    // clips the overflow and no scrollbar ever appears. Every scrollable
    // descendant in this pane needs the `minHeight: 0` opt-out.
    minHeight: 0,
  } satisfies CSSProperties,
  treeLabel: {
    fontSize: 10.5,
    fontWeight: 700,
    color: "var(--text-muted)",
    letterSpacing: "0.05em",
    padding: "2px 8px 8px",
  } satisfies CSSProperties,
  treeRow: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 7,
    width: "100%",
    textAlign: "left",
    padding: "5px 8px",
    borderRadius: 5,
    border: "none",
    cursor: "pointer",
    fontSize: 12,
    fontFamily: "inherit",
    background: active ? "var(--accent-bg)" : "transparent",
    color: active ? "var(--accent-text)" : "var(--text-secondary)",
  }),
  pane: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    // Both as a grid item (of `previewWrap`) and as a flex container, this box
    // defaults to sizing by content. Without `minHeight: 0` a long file makes it
    // taller than the 340px track, `previewWrap`'s `overflow: hidden` clips the
    // excess, and `paneBody`'s `overflow: auto` never has anything to scroll.
    minHeight: 0,
  } satisfies CSSProperties,
  paneHead: {
    padding: "8px 12px",
    borderBottom: "1px solid var(--border)",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  panePath: { fontSize: 12, flex: 1, minWidth: 0 } satisfies CSSProperties,
  paneBody: {
    margin: 0,
    padding: 14,
    fontSize: 11.5,
    lineHeight: 1.6,
    overflow: "auto",
    flex: 1,
    minHeight: 0,
    color: "var(--text-primary)",
    background: "var(--code-bg)",
    whiteSpace: "pre",
  } satisfies CSSProperties,
  paneEditor: {
    margin: 0,
    padding: 14,
    fontSize: 11.5,
    lineHeight: 1.6,
    flex: 1,
    minHeight: 0,
    width: "100%",
    resize: "none",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
    background: "var(--code-bg)",
  } satisfies CSSProperties,
  placeholder: {
    padding: 14,
    fontSize: 12,
    color: "var(--text-muted)",
    background: "var(--code-bg)",
    flex: 1,
    minHeight: 0,
  } satisfies CSSProperties,

  /* --- Configure step (:74-87) --- */
  step: { maxWidth: 600 } satisfies CSSProperties,
  chipRow: { display: "flex", flexWrap: "wrap", gap: 7 } satisfies CSSProperties,
  radioList: {
    display: "flex",
    flexDirection: "column",
    gap: 7,
  } satisfies CSSProperties,
  radioLabel: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    fontSize: 13,
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  radioDot: (selected: boolean): CSSProperties => ({
    width: 16,
    height: 16,
    borderRadius: 99,
    border: "1.5px solid " + (selected ? "var(--accent)" : "var(--border-strong)"),
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  }),
  radioInner: {
    width: 8,
    height: 8,
    borderRadius: 99,
    background: "var(--accent)",
  } satisfies CSSProperties,
  hint: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    marginTop: 8,
  } satisfies CSSProperties,
  infoCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "11px 13px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  infoText: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  regenNotice: {
    display: "flex",
    alignItems: "flex-start",
    gap: 9,
    marginBottom: 16,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,

  /* --- Install step (:89-101) --- */
  installCard: {
    width: "100%",
    textAlign: "left",
    padding: 18,
    borderRadius: 10,
    border: "1.5px solid var(--accent)",
    background: "var(--accent-bg)",
    cursor: "pointer",
    marginBottom: 12,
    fontFamily: "inherit",
  } satisfies CSSProperties,
  installHead: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  } satisfies CSSProperties,
  installTitle: { fontSize: 14, fontWeight: 700 } satisfies CSSProperties,
  installBody: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
    margin: 0,
  } satisfies CSSProperties,
  zipCard: {
    width: "100%",
    textAlign: "left",
    padding: 16,
    borderRadius: 10,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    cursor: "pointer",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  zipRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  zipTitle: { fontSize: 13.5, fontWeight: 600 } satisfies CSSProperties,
  zipHint: {
    marginLeft: "auto",
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  note: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    marginTop: 14,
    textAlign: "center",
    lineHeight: 1.6,
  } satisfies CSSProperties,
  docsLink: { color: "var(--accent-text)" } satisfies CSSProperties,

  /* --- Configure step: expected Actions secrets --- */
  secretList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  secretRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  secretName: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-primary)",
    flexShrink: 0,
  } satisfies CSSProperties,
  secretDesc: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    flex: 1,
    minWidth: 0,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  successCard: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--ok)",
    background: "var(--ok-bg)",
    marginBottom: 12,
    fontSize: 13,
  } satisfies CSSProperties,
  errorCard: {
    display: "flex",
    alignItems: "flex-start",
    gap: 9,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    marginBottom: 12,
    fontSize: 12.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
};
